//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise_0505 {
    
    
    public partial class Default {
        
        protected System.Web.UI.WebControls.Literal h1;
        
        protected System.Web.UI.WebControls.Table table1;
        
        protected System.Web.UI.WebControls.Label lbSelect;
        
        protected System.Web.UI.WebControls.DropDownList dList;
    }
}
