//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise_0505 {
    
    
    public partial class SiteMaster {
        
        protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
